### ISSUE TITLE
Cannot drag courses to term 3 column

### ISSUE THREAD

**Issue by circles-slave** [csesoc/Circles#1047] opened 2023-04-13 01:25 UTC
Some courses (for example comp6080 and comp3311) are being offered in 23T1 but I am unable to drag them to this section.

**Comment by imagine-hussain** [comment] 2023-08-05 08:20
Am unable to reproduce. Perhaps you have locked the term. 
<img width="431" alt="image" src="https://github.com/csesoc/circles/assets/93496985/f8a30aaf-28dd-411f-a78a-5d66743b6d36">

Try to unlock with this button, should then be draggable.

Closing for now. Will re-open if more detail to reproducibility is given.

<img width="90" alt="image" src="https://github.com/csesoc/circles/assets/93496985/f4258dfc-cd47-441a-96be-cff55efb8dd3">

**Closed as completed** 2023-08-05 08:20 UTC
