### ISSUE TITLE
"You should never see this" in term planner

### ISSUE THREAD

**Issue by circles-slave** [csesoc/Circles#634] opened 2022-07-26 03:04 UTC
Ah i dont know, sometimes circles just opens to white and i cant see anything. I've just been doing tonnes of shuffling anf adding plus removing courses.

Here's the error report
Error

{"fileName":"https://circles.csesoc.app/assets/index.8a11fd3b.js","lineNumber":2486,"columnNumber":287,"message":"a[e] is undefined"}
Error Info

t@https://circles.csesoc.app/assets/index.8a11fd3b.js:1602:12664 L3e@https://circles.csesoc.app/assets/index.8a11fd3b.js:1655:18922 div m@https://circles.csesoc.app/assets/index.8a11fd3b.js:93:7159 div LS@https://circles.csesoc.app/assets/index.8a11fd3b.js:326:1005 oMr@https://circles.csesoc.app/assets/index.8a11fd3b.js:2627:954 lVe@https://circles.csesoc.app/assets/index.8a11fd3b.js:81:6231 sVe@https://circles.csesoc.app/assets/index.8a11fd3b.js:81:5716 fVe@https://circles.csesoc.app/assets/index.8a11fd3b.js:90:477 KVe@https://circles.csesoc.app/assets/index.8a11fd3b.js:93:5115 P0t@https://circles.csesoc.app/assets/index.8a11fd3b.js:227:82 sMr@https://circles.csesoc.app/assets/index.8a11fd3b.js:2627:3612 t@https://circles.csesoc.app/assets/index.8a11fd3b.js:72:15366 oje@https://circles.csesoc.app/assets/index.8a11fd3b.js:72:910

**Comment by Peedee2002** [comment] 2022-08-17 10:18
@gtangelo i assume this is resolved by us removing the animations for course addition?

**Comment by gtangelo** [comment] 2022-08-17 10:29
> @gtangelo i assume this is resolved by us removing the animations for course addition?

Totally unrelated error from it haha. Think this was caused by a planner state bug before.

Umm i left this issue open as a reminder to add more useful info on the error page (i.e. planner redux state) as thats another major source of bugs that could occur. But we can close this issue since I already created a ticket for it 😎

**Closed as completed** 2022-08-17 10:29 UTC
